---
efiBootLoader: "grub"
efiBootloaderId: "ubuntu"
kernel: "/vmlinuz"
img: "/initrd.img"
fallback: "/vmlinuz"
fallbackImg: "/initrd.img"
timeout: "5"
bootloaderCommandLine: "quiet splash"
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"
installEpoxy: false
installEFIFallback: true
