---
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 300M
efiSystemPartitionType: "fat32"

userSwapChoices:
    - none
    - small
    - suspend
    - file

drawNestedPartitions: false
alwaysShowPartitionLabels: true
initialPartitioningChoice: erase
initialSwapChoice: none
defaultFileSystemType: "ext4"
availableFileSystemTypes:
    - "ext4"
    - "btrfs"
    - "xfs"
