---
defaultGroups:
    - sudo
    - audio
    - video
    - netdev
    - plugdev
    - cdrom
    - dip
    - users

autologinGroup: autologin
doAutologin: false
sudoersGroup: sudo
setRootPassword: false
doReusePassword: true
